#version: "3.7"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coopvote
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    #platform: linux/amd64

  app:
    build: ../../
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SLEEP_APPLICATION: 10
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coopvote
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
